import type { Config } from "tailwindcss";

const config = {
  theme: {
    extend: {
      colors: {
        brand: "var(--brand)",
        "brand-mid": "var(--brand-mid)",
        "brand-light": "var(--brand-light)",
        gold: "var(--gold)",
        "gold-foreground": "var(--gold-foreground)",
        "gold-hover": "var(--gold-hover)",
        "brand-50": "var(--brand-50)",
        "brand-100": "var(--brand-100)",
        "brand-200": "var(--brand-200)",
        "brand-300": "var(--brand-300)",
        "brand-400": "var(--brand-400)",
        "brand-500": "var(--brand-500)",
        "brand-600": "var(--brand-600)",
        "brand-700": "var(--brand-700)",
        "brand-800": "var(--brand-800)",
        "brand-900": "var(--brand-900)",
        "brand-950": "var(--brand-950)",
        "gold-50": "var(--gold-50)",
        "gold-100": "var(--gold-100)",
        "gold-200": "var(--gold-200)",
        "gold-300": "var(--gold-300)",
        "gold-400": "var(--gold-400)",
        "gold-500": "var(--gold-500)",
        "gold-600": "var(--gold-600)",
        "gold-700": "var(--gold-700)",
        "gold-800": "var(--gold-800)",
        "gold-900": "var(--gold-900)",
        "gold-950": "var(--gold-950)",
        surface: "var(--surface)",
        "surface-low": "var(--surface-low)",
        "surface-high": "var(--surface-high)",
        ink: "var(--ink)",
        "ink-2": "var(--ink-2)",
        "ink-3": "var(--ink-3)",
        glass: "var(--glass-bg)",
        "glass-border": "var(--glass-border)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        popover: "var(--popover)",
        primary: "var(--primary)",
        "primary-hover": "var(--primary-hover)",
        secondary: "var(--secondary)",
        muted: "var(--muted)",
        accent: "var(--accent)",
        destructive: "var(--destructive)",
        success: "var(--success)",
        warning: "var(--warning)",
        "footer-bg": "var(--footer-bg)",
        "on-surface": "var(--on-surface)",
        "on-surface-muted": "var(--on-surface-muted)",
        "outline-variant": "var(--outline-variant)",
        "nav-glass-bg": "var(--nav-glass-bg)",
        "nav-glass-border": "var(--nav-glass-border)",
        "surface-lowest": "var(--surface-lowest)",
        "primary-tint": "var(--primary-tint)",
        "amber-tint": "var(--amber-tint)",
        "green-tint": "var(--green-tint)",
        line: "var(--line)",
        "line-2": "var(--line-2)",
        danger: "#C2410C",
        info: "var(--primary)",
      },
      fontFamily: {
        serif: ["var(--font-onest)", "system-ui", "sans-serif"],
        sans: ["var(--font-onest)", "system-ui", "sans-serif"],
        display: ["var(--font-onest)", "system-ui", "sans-serif"],
      },
      spacing: {
        "nav-h": "var(--nav-h)",
        "sec-pad": "var(--sec-pad)",
      },
      maxWidth: {
        page: "var(--max-w)",
      },
      borderRadius: {
        glass: "var(--glass-radius)",
        card: "var(--card-radius)",
        pill: "var(--radius-pill)",
        step: "var(--radius-step)",
        hero: "var(--radius-hero)",
      },
      boxShadow: {
        glass: "var(--glass-shadow)",
        card: "var(--card-shadow)",
        editorial: "0 28px 80px rgba(33,49,63,0.14)",
        lift: "var(--shadow-lift)",
      },
    },
  },
} satisfies Config;

export default config;
