-- Seed: туры (>=6) с маршрутами 3-5 остановок.
-- Поля travelToNextMinutes и transportOptions сохранены в JSON внутри description.

insert into public.listings (
  id,
  guide_id,
  slug,
  title,
  region,
  city,
  category,
  route_summary,
  description,
  duration_minutes,
  max_group_size,
  price_from_minor,
  currency,
  private_available,
  group_available,
  instant_book,
  meeting_point,
  inclusions,
  exclusions,
  cancellation_policy_key,
  status,
  featured_rank
)
values
  (
    '20000000-0000-4000-8000-000000000001',
    '10000000-0000-4000-8000-000000000101',
    'elista-steppe-khurul-city-chess',
    'Элиста за день: центр, хурул и Сити-Чесс',
    'Калмыкия',
    'Элиста',
    'Культурно-исторический маршрут',
    'Пагода Семи Дней -> Хурул -> Сити-Чесс -> Степной обзор',
    jsonb_build_object(
      'imageUrl', 'https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1600&h=1200&q=80',
      'itinerary', jsonb_build_array(
        jsonb_build_object('title', 'Пагода Семи Дней', 'durationHours', 1.2, 'travelToNextMinutes', 15, 'transportOptions', jsonb_build_array('walking', 'taxi', 'own_car')),
        jsonb_build_object('title', 'Золотая обитель Будды Шакьямуни', 'durationHours', 1.5, 'travelToNextMinutes', 20, 'transportOptions', jsonb_build_array('city_bus', 'taxi', 'own_car')),
        jsonb_build_object('title', 'Сити-Чесс', 'durationHours', 1.0, 'travelToNextMinutes', 35, 'transportOptions', jsonb_build_array('taxi', 'own_car', 'guide_transport')),
        jsonb_build_object('title', 'Смотровая точка в степи', 'durationHours', 1.0)
      ),
      'notes', 'Маршрут подходит для группы, которая хочет сочетать город и природу в один день.'
    )::text,
    420,
    8,
    780000,
    'RUB',
    true,
    true,
    false,
    'Элиста, Пагода Семи Дней',
    array['Услуги гида', 'Трансфер между локациями'],
    array['Питание', 'Личные расходы'],
    'flexible',
    'published',
    1
  ),
  (
    '20000000-0000-4000-8000-000000000002',
    '10000000-0000-4000-8000-000000000102',
    'kazan-kremlin-old-tatar-quarter',
    'Казань: кремль, Старо-Татарская слобода и вечерняя набережная',
    'Татарстан',
    'Казань',
    'Городской маршрут',
    'Казанский кремль -> Слобода -> Озеро Кабан -> Набережная',
    jsonb_build_object(
      'imageUrl', 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&h=1200&q=80',
      'itinerary', jsonb_build_array(
        jsonb_build_object('title', 'Казанский кремль', 'durationHours', 1.5, 'travelToNextMinutes', 12, 'transportOptions', jsonb_build_array('walking', 'taxi')),
        jsonb_build_object('title', 'Старо-Татарская слобода', 'durationHours', 1.3, 'travelToNextMinutes', 10, 'transportOptions', jsonb_build_array('city_bus', 'taxi', 'own_car')),
        jsonb_build_object('title', 'Озеро Кабан', 'durationHours', 1.0, 'travelToNextMinutes', 15, 'transportOptions', jsonb_build_array('walking', 'taxi')),
        jsonb_build_object('title', 'Набережная Казанки', 'durationHours', 1.0)
      ),
      'notes', 'Сбалансированный маршрут для тех, кто хочет и исторический контекст, и городскую атмосферу.'
    )::text,
    360,
    8,
    860000,
    'RUB',
    true,
    true,
    false,
    'Казань, у башни Сююмбике',
    array['Услуги гида', 'Билеты в кремль'],
    array['Питание', 'Личные покупки'],
    'flexible',
    'published',
    2
  ),
  (
    '20000000-0000-4000-8000-000000000003',
    '10000000-0000-4000-8000-000000000103',
    'spb-classic-city-and-gulf',
    'Санкт-Петербург: дворцовый центр и выезд к Финскому заливу',
    'Ленобласть',
    'Санкт-Петербург',
    'Культурный маршрут',
    'Невский -> Дворцовая -> Васильевский -> Кронштадт',
    jsonb_build_object(
      'imageUrl', 'https://images.unsplash.com/photo-1520637836862-4d197d17c55a?auto=format&fit=crop&w=1600&h=1200&q=80',
      'itinerary', jsonb_build_array(
        jsonb_build_object('title', 'Невский проспект', 'durationHours', 1.0, 'travelToNextMinutes', 10, 'transportOptions', jsonb_build_array('walking', 'city_bus', 'taxi')),
        jsonb_build_object('title', 'Дворцовая площадь', 'durationHours', 1.2, 'travelToNextMinutes', 25, 'transportOptions', jsonb_build_array('city_bus', 'taxi', 'own_car')),
        jsonb_build_object('title', 'Стрелка Васильевского острова', 'durationHours', 1.0, 'travelToNextMinutes', 55, 'transportOptions', jsonb_build_array('taxi', 'own_car', 'guide_transport')),
        jsonb_build_object('title', 'Кронштадт, Якорная площадь', 'durationHours', 1.2)
      ),
      'notes', 'Подходит для группы, которая хочет соединить центр Петербурга и морское направление за один день.'
    )::text,
    510,
    6,
    990000,
    'RUB',
    true,
    true,
    false,
    'Санкт-Петербург, Гостиный двор',
    array['Услуги гида', 'Транспорт в Кронштадт'],
    array['Музейные билеты', 'Питание'],
    'moderate',
    'published',
    3
  ),
  (
    '20000000-0000-4000-8000-000000000004',
    '10000000-0000-4000-8000-000000000104',
    'sochi-sea-park-mountain-view',
    'Сочи: морская набережная, парк и обзор Красной Поляны',
    'Краснодарский край',
    'Сочи',
    'Смешанный маршрут',
    'Морпорт -> Ривьера -> Олимпийский парк -> Красная Поляна',
    jsonb_build_object(
      'imageUrl', 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1600&h=1200&q=80',
      'itinerary', jsonb_build_array(
        jsonb_build_object('title', 'Морской порт и набережная', 'durationHours', 1.1, 'travelToNextMinutes', 18, 'transportOptions', jsonb_build_array('walking', 'taxi')),
        jsonb_build_object('title', 'Парк Ривьера', 'durationHours', 1.0, 'travelToNextMinutes', 35, 'transportOptions', jsonb_build_array('city_bus', 'taxi', 'own_car')),
        jsonb_build_object('title', 'Олимпийский парк', 'durationHours', 1.2, 'travelToNextMinutes', 65, 'transportOptions', jsonb_build_array('taxi', 'own_car', 'guide_transport')),
        jsonb_build_object('title', 'Красная Поляна (обзорная точка)', 'durationHours', 1.3)
      ),
      'notes', 'Маршрут для тех, кто хочет увидеть и побережье, и горную часть региона в один день.'
    )::text,
    540,
    7,
    1120000,
    'RUB',
    true,
    true,
    false,
    'Сочи, Морской вокзал',
    array['Услуги гида', 'Транспорт между локациями'],
    array['Канатная дорога', 'Питание'],
    'moderate',
    'published',
    4
  ),
  (
    '20000000-0000-4000-8000-000000000005',
    '10000000-0000-4000-8000-000000000105',
    'baikal-irkutsk-listvyanka-olkhon-preview',
    'Байкал: Иркутск, Листвянка и обзорный маршрут к Ольхону',
    'Иркутская область',
    'Иркутск',
    'Природный маршрут',
    'Иркутск -> Листвянка -> Тажеранские степи -> Ольхон',
    jsonb_build_object(
      'imageUrl', 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1600&h=1200&q=80',
      'itinerary', jsonb_build_array(
        jsonb_build_object('title', 'Старый Иркутск', 'durationHours', 1.0, 'travelToNextMinutes', 70, 'transportOptions', jsonb_build_array('taxi', 'own_car', 'guide_transport')),
        jsonb_build_object('title', 'Листвянка и берег Байкала', 'durationHours', 1.5, 'travelToNextMinutes', 120, 'transportOptions', jsonb_build_array('own_car', 'guide_transport')),
        jsonb_build_object('title', 'Тажеранские степи', 'durationHours', 1.4, 'travelToNextMinutes', 95, 'transportOptions', jsonb_build_array('own_car', 'guide_transport')),
        jsonb_build_object('title', 'Ольхон (обзорная точка)', 'durationHours', 1.2)
      ),
      'notes', 'Программа рассчитана на длительные переезды и комфортный темп с обязательными остановками.'
    )::text,
    720,
    5,
    1480000,
    'RUB',
    true,
    true,
    false,
    'Иркутск, 130-й квартал',
    array['Услуги гида', 'Транспорт', 'Термос с чаем'],
    array['Паром', 'Питание', 'Проживание'],
    'strict',
    'published',
    5
  ),
  (
    '20000000-0000-4000-8000-000000000006',
    '10000000-0000-4000-8000-000000000102',
    'moscow-historic-center-and-estates',
    'Москва и Подмосковье: центр столицы и усадебный выезд',
    'МО',
    'Москва',
    'Город + загород',
    'Зарядье -> Арбат -> Коломенское -> Архангельское',
    jsonb_build_object(
      'imageUrl', 'https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&w=1600&h=1200&q=80',
      'itinerary', jsonb_build_array(
        jsonb_build_object('title', 'Парк Зарядье', 'durationHours', 0.9, 'travelToNextMinutes', 20, 'transportOptions', jsonb_build_array('walking', 'city_bus', 'taxi')),
        jsonb_build_object('title', 'Старый Арбат', 'durationHours', 1.0, 'travelToNextMinutes', 35, 'transportOptions', jsonb_build_array('city_bus', 'taxi', 'own_car')),
        jsonb_build_object('title', 'Коломенское', 'durationHours', 1.2, 'travelToNextMinutes', 60, 'transportOptions', jsonb_build_array('taxi', 'own_car', 'guide_transport')),
        jsonb_build_object('title', 'Усадьба Архангельское', 'durationHours', 1.3)
      ),
      'notes', 'Маршрут сочетает городскую прогулку и выезд за МКАД в одном запросе.'
    )::text,
    600,
    8,
    1050000,
    'RUB',
    true,
    true,
    false,
    'Москва, метро Китай-город',
    array['Услуги гида', 'Транспорт между точками'],
    array['Входные билеты', 'Питание'],
    'moderate',
    'published',
    6
  )
on conflict (id) do update
set
  guide_id = excluded.guide_id,
  slug = excluded.slug,
  title = excluded.title,
  region = excluded.region,
  city = excluded.city,
  category = excluded.category,
  route_summary = excluded.route_summary,
  description = excluded.description,
  duration_minutes = excluded.duration_minutes,
  max_group_size = excluded.max_group_size,
  price_from_minor = excluded.price_from_minor,
  currency = excluded.currency,
  private_available = excluded.private_available,
  group_available = excluded.group_available,
  instant_book = excluded.instant_book,
  meeting_point = excluded.meeting_point,
  inclusions = excluded.inclusions,
  exclusions = excluded.exclusions,
  cancellation_policy_key = excluded.cancellation_policy_key,
  status = excluded.status,
  featured_rank = excluded.featured_rank,
  updated_at = timezone('utc', now());
